version: '3.4'

services:

  postgres:
    container_name: backend-postgres
    image: postgres:latest
    hostname: localhost
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=senhaS3creta
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
